services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ticketing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"                # Expose DB to host for local tools (pgAdmin/psql)
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persist data between restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

# App service (uncomment to run the app in Docker alongside DB)
#  app:
#    build: .                       # Builds Dockerfile in this directory
#    restart: always
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/invoicing_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
#      SPRING_FLYWAY_ENABLED: true
#    ports:
#      - "8080:8080"               # Map container port to host

volumes:
  postgres_data: